# Usar una imagen base de Node
FROM node:18-alpine

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar los archivos de definición de paquete
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar todos los archivos del proyecto al contenedor
COPY . .

# Compilar el proyecto TypeScript
RUN npm run build

# Exponer el puerto que el servidor Node usará
EXPOSE 3000

# Comando para ejecutar la aplicación compilada
CMD ["node", "dist/app.js"]
